server:
  port: 8082

spring:
  application:
    name: spring-boot-security
  datasource:
    url: jdbc:mysql://localhost:3306/gym_security?createDatabaseIfNotExist=True
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  expiration: ${JWT_EXPRIRATION:900000} #15minutos
  key: ${JWT_KEY:CqB8d6 axnuffpv54_CJF!&I0ujimBdcc$aaZF 6F$_p3xsma&Mr3yHJ&Er9lZ=nK_97z!JIFrwbopH&Ie!a9iNaybuTA8R9qUY 21$Cbu5f1WA6eSNZ5qyfI#0sr!EIl&by!z$9FEvXTcixa5C_t5XMrx-TuKTHI FKbGi37d72hUX_Fe$2ixFPHzpq9PvCnDu#NINpak5U t5CU=y#nhODoL5Y_aahuzjxS0XKEF6&phoLs  1X9j8CiHm5FHzYwXt#a-3WQDv=XO3gqX85$8#Zy_TecBI47- 5BtsgrUEvoI9aeMIjvsQpMbZSzIRXpaV=P&OQ8szaW!K$iqn2Ro&}
